### PR TITLE
Update Swifts, SwiftyJSON, Xcode 8

### PR DESCRIPTION
**Pull request by carlthuringer**
@bellycard/platform 

In trying to get Barco to build, I found that SwiftyJSON needed to be upgraded; and it was being version-blocked by this thingy.

I tried to minimize my tweaks, but there were a couple of syntax/type errors I couldn't figure out.

### CODE REVIEW

**Review by sisk — COMMENTED** [review]
were these necessary changes for XCode 7.3 to build barco?

**Comment by carlthuringer** [comment]
@sisk No, they were not. This is necessary for xcode 8.x

**Review by jonhoman — APPROVED** [review]
Sure??? I can't really make heads or tails of this. But seemingly it's necessary moving forward. Good on green.

**Comment by carlthuringer** [comment]
Yeah I have to bang on circleci a little more... it's also evolved from under this code and I think reducing it back to basics will help.

I'd also like to un-disable the broken test, but I barely know how to Swift and the XCTest api is not clear to me... 

This Pod is very abstract. I'm still not totally sure what it's for. Wish there was an actual readme.

**Pull request merged**
